### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by eftanzer** [snyk/parlay#12]
Attempting to install v0.1.4 on a Mac (Apple M1 Max)

[Installation docs](https://github.com/snyk/parlay) show:
```
wget https://github.com/snyk/parlay/releases/download/v{version}/parlay_{version}_Darwin_arm64.tar.gz
tar -xvf parlay_{version}_Darwin_arm64.tar.gz
```

*Note that the `v` in `download/v{version}/` should be removed resulting in `download/v{version}/` 

Inserting a version (v0.1.4) results in the following commands:
```
wget https://github.com/snyk/parlay/releases/v0.1.4/parlay_v0.1.4_Darwin_arm64.tar.gz
tar -xvf parlay_v0.1.4_Darwin_arm64.tar.gz
```

This fails with the following response:
```
--2023-06-09 13:15:09--  https://github.com/snyk/parlay/releases/v0.1.4/parlay_v0.1.4_Darwin_arm64.tar.gz
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-09 13:15:10 ERROR 404: Not Found.

tar: Error opening archive: Failed to open 'parlay_v0.1.4_Darwin_arm64.tar.gz'
```

Replacing the first line of the command with the following results in a successful download of the file:
```
wget https://github.com/snyk/parlay/releases/tag/v0.1.4/parlay_v0.1.4_Darwin_arm64.tar.gz
```

But the command `tar -xvf parlay_v0.1.4_Darwin_arm64.tar.gz` or `tar -xzf parlay_v0.1.4_Darwin_arm64.tar.gz` results in an error:
```
tar: Error opening archive: Unrecognized archive format
```

I wasn't able to move the needle further with manual downloads or unzip attempts.

**Comment by garethr** [comment]
Fixed instructions in https://github.com/snyk/parlay/commit/7564d0757605cb40070a6d5fa13c87b0d78ae92c

Let me know if those works for you now. Some changes in the release script changed the file name I think.
