### ISSUE TITLE
Support enriching SPDX SBOMs

### ISSUE THREAD

**Issue by garethr** [snyk/parlay#3]
Currently `parlay` only support CycloneDX. Implementing for SPDX would be useful, though not all information may be applicable to the SPDX spec.

**Comment by mcombuechen** [comment]
Hey @garethr 
happy to take a stab at this. I think we need a sort of strategy pattern solution that invokes different code based on whether handling CycloneDX or SPDX.

Some questions:
1. Are the contents of `lib` intended to be used by 3rd party tools outside of parlay? (I think this would be great, maybe we rename the directory to `pkg` to make it more Golang idiomatic)
2. The `enrich` interface (`enrichSBOM` functions in `lib` that is) is currently bytes in, bytes out, which is a pleasant UX. However, it would require us to apply brute force to understand the given SBOM in a sea of possible permutations (CycloneDX? SPDX? Schema version? XML? JSON? YAML? Text?). Should the interface change to require the SBOM schema, or do we want to invest in a brute force solution?

**Comment by mcombuechen** [comment]
Draft PR open here: https://github.com/snyk/parlay/pull/20

**Comment by goneall** [comment]
> I had a play with the brute-force idea https://github.com/snyk/parlay/pull/20. It lead me to believe that we need to extend the interface beyond just bytes and ask consumers to specify the given format, I see too many cons otherwise. WDYT?

@garethr I tend to agree with @mcombuechen - the brute force could be problematic.

**Comment by mcombuechen** [comment]
@garethr Should we close this issue?

**Comment by garethr** [comment]
Now shipped in v0.2.0
