### ISSUE TITLE
Error when try to scan .xml SBOM

### ISSUE THREAD

**Issue by Denimoll** [snyk/parlay#32]
```
# parlay ecosystems enrich testing/sbom.cyclonedx.xml
2:00PM FTL Input needs to be a valid CycloneDX SBOM error="invalid character '<' looking for beginning of value"
```

I'm trying to enrich sbom from your testing directory.

**Comment by garethr** [comment]
The support for XML was in main, but not in the released version (0.1.5). It's not available in the latest version (0.2.0). Thanks for letting us know.
