### ISSUE TITLE
No information found for components with a group

### ISSUE THREAD

**Issue by StefanFl** [snyk/parlay#56]
My CycloneDX includes components like 

```json
    {
        "type": "library",
        "bom-ref": "@emotion/react@11.11.3",
        "group": "@emotion",
        "name": "react",
        "version": "11.11.3",
        "purl": "pkg:npm/%40emotion/react@11.11.3"
    },
```

Parly doesn't find any information for this component when using `ecosystems enrich`.

For other components like

```json
    {
        "type": "library",
        "bom-ref": "regenerator-runtime@0.14.1",
        "name": "regenerator-runtime",
        "version": "0.14.1",
        "purl": "pkg:npm/regenerator-runtime@0.14.1"
    },
```

Parlay finds additional information.

The only differences is the `group` in the first kind of components. Do you have any idea, why it is not working with the `group`?

**Comment by mcombuechen** [comment]
Hey @StefanFl just letting you know that we've identified the bug and opened a PR to fix this, which we will merge and release soon. Thanks for reporting this!

**Comment by mcombuechen** [comment]
This has now been released in https://github.com/snyk/parlay/releases/tag/v0.2.3.

**Comment by StefanFl** [comment]
Awesome, thank you very much
