### ISSUE TITLE
Support CycloneDX specification 1.6

### ISSUE THREAD

**Issue by Weissger** [snyk/parlay#71]
I really like Parlay. Thank you very much for it.

Are there any plans to support CycloneDX specification 1.6? I would prefer not to "derich" my data by down-converting SBOMS to 1.5 before enriching them with Parlay. 😄

**Comment by mcombuechen** [comment]
Hey @Weissger 

thanks for opening this thread, and please excuse the delayed response. [We just released a new version with CycloneDX 1.6 support](https://github.com/snyk/parlay/releases/tag/v0.5.1).

Happy to receive any feedback whether it works or doesn't work for you! 🤗
