### ISSUE TITLE
Parlay error related to supplier with enriching SPDX JSON

### ISSUE THREAD

**Issue by goneall** [snyk/parlay#92]
When enriching the attached file, the following error is generated:

```
2:36AM FTL Failed to encode new SBOM error="json: error calling MarshalJSON for type *common.Supplier: failed to marshal invalid Supplier: {Supplier: SupplierType:Organization}"
```

Here's the JSON file being enriched: 
[o-ran-int-trivy-spdx.json.txt](https://github.com/user-attachments/files/18053820/o-ran-int-trivy-spdx.json.txt)

Parlay version 0.6.0 was used.

Note related: https://github.com/lfscanning/scaffold/issues/131

**Comment by goneall** [comment]
I'll do some debugging and attach a debug output later today.

**Comment by goneall** [comment]
I've isolated the problem.

If the name of the supplier includes a parenthesis `(`, it will try to interpret it as an email address per the SPDX spec.

A solution would be to do a string replacement of `(` with `[` and `)` with `]` before this line:

https://github.com/snyk/parlay/blob/b0523a0670c92442860900d4c4e94bb5c1a3d8f5/lib/ecosystems/enrich_spdx.go#L80

**Comment by goneall** [comment]
Narrowed the issue down.

It has to do with blank supplier names not being valid.

To fix this, we just need to add a check for empty strings in the conditional at:

https://github.com/snyk/parlay/blob/b0523a0670c92442860900d4c4e94bb5c1a3d8f5/lib/ecosystems/enrich_spdx.go#L78

**Comment by goneall** [comment]
I tested the following replacement for line 78 and it resolved the issue:

```
if name, ok := ownerRecord["name"].(string); ok && len(name) > 0 {
```

**Comment by mcombuechen** [comment]
Thanks @goneall for reporting, this should be a quick fix. 🙂

**Comment by goneall** [comment]
Thanks @mcombuechen
